[package]
name = "wmlua"
version = "0.1.0"
edition = "2021"
authors = ["tickbh <tickdream125@hotmail.com>"]
description = "about algorithm data structure, now has lru/lru-k/lfu/slab/rbtree/roaring_bitmap, 关于算法常用的数据结构"
repository = "https://github.com/tickbh/wmlua"
license = "Apache-2.0"
keywords = ["algorithm", "lru", "lfu", "lru-k", "slab"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
